version: "3"
services:
  postgres:
    image: postgres:12.2
    restart: always
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
  history_tools:
    image: eosio/eosio-explorer:fill-pg-1.2
    restart: always
    container_name: history_tools
    user: ${UID}
    depends_on:
      - postgres
    env_file: .env
    command: ./build/fill-pg --fpg-create --ignore-onblock --remove_old_delta_row --dbstring="hostaddr=${POSTGRES_HOST} port=${POSTGRES_PORT}" --fill-connect-to ${LEDGIS_ENDPOINT}
